version: '3.7'
services:
  prometheus:
    image: prom/prometheus:latest
    network_mode: host
    volumes:
      - ./apim-prometheus-client/prometheus.yml:/etc/prometheus/prometheus.yml

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=quarkus
    ports:
      - "5432:5432"
