version: '3.7'
services:

  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  prometheus:
    image: prom/prometheus:latest
    network_mode: host
    volumes:
      - ./apim-prometheus-client/prometheus.yml:/etc/prometheus/prometheus.yml

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=quarkus
    ports:
      - "5432:5432"
