global:
  scrape_interval: 15s

  external_labels:
    monitor: 'apim-monitor'

scrape_configs:
  - job_name: 'apim-scraper'
    metrics_path: '/q/metrics'
    scrape_interval: 2s
    static_configs:
      - targets: ['localhost:8080']
